#!/usr/bin/env python3
"""Render the all-reviews canvas .tsx with the per-review data inlined.

The canvas template uses a `__DATA_JSON__` placeholder. We replace it with
a JSON string literal (backticks + dollar-signs escaped for the template
string form) so the canvas can parse the data at load time without
needing any network access.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORKSPACE = Path("/Users/Ishaan/.cursor/projects/Users-Ishaan-Zomato-Scraper")
CANVAS_PATH = WORKSPACE / "canvases/zomato-extraction-all-reviews.canvas.tsx"

TEMPLATE = r"""// AUTO-GENERATED by scripts/extraction/render_all_reviews_canvas.py
// Inlined: all 146 reviews from the v2 sample (Gemini 2.5 Flash Lite, sync, t=0).
// Re-run the renderer if the underlying data file changes.

import {
  Callout,
  Card,
  CardBody,
  CardHeader,
  Code,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Text,
  TextInput,
  useCanvasState,
  useHostTheme,
} from "cursor/canvas";

type Extraction = Record<string, unknown>;

type ReviewRecord = {
  idx: number;
  restaurant: string;
  rating: number | null;
  source: string;
  desc_len: number;
  desc: string;
  ext: Extraction;
  warns: string[];
  in_tok: number;
  out_tok: number;
};

const DATA_JSON = `__DATA_JSON__`;
const ALL_REVIEWS: ReviewRecord[] = JSON.parse(DATA_JSON);

// ---------------------------------------------------------------------------

function severityTone(sev: string): "danger" | "warning" | "info" | "neutral" {
  if (sev === "severe") return "danger";
  if (sev === "moderate") return "warning";
  if (sev === "mild") return "info";
  return "neutral";
}

function sentimentTone(s: string): "success" | "danger" | "warning" | "info" | "neutral" {
  if (s === "loved" || s === "liked") return "success";
  if (s === "disliked" || s === "hated") return "danger";
  if (s === "neutral") return "neutral";
  return "info";
}

function ratingTone(r: number | null): "success" | "danger" | "warning" | "neutral" {
  if (r === null) return "neutral";
  if (r <= 2) return "danger";
  if (r >= 4) return "success";
  return "warning";
}

function ratingBucket(r: number | null): string {
  if (r === null) return "?";
  if (r <= 1.5) return "1";
  if (r <= 2.5) return "2";
  if (r <= 3.5) return "3";
  if (r <= 4.5) return "4";
  return "5";
}

// ---------------------------------------------------------------------------

const RATING_OPTIONS: { label: string; value: string }[] = [
  { label: "all", value: "all" },
  { label: "1\u2605", value: "1" },
  { label: "2\u2605", value: "2" },
  { label: "3\u2605", value: "3" },
  { label: "4\u2605", value: "4" },
  { label: "5\u2605", value: "5" },
];

const SOURCE_OPTIONS = [
  { label: "all sources", value: "all" },
  { label: "reviews", value: "reviews" },
  { label: "rescrape", value: "rescrape" },
];

const CONTENT_OPTIONS = [
  { label: "all", value: "all" },
  { label: "with extraction", value: "with_extraction" },
  { label: "empty {}", value: "empty" },
  { label: "with warnings", value: "with_warnings" },
];

export default function AllReviewsCanvas() {
  const [ratingFilter, setRatingFilter] = useCanvasState<string>("rating", "all");
  const [sourceFilter, setSourceFilter] = useCanvasState<string>("source", "all");
  const [contentFilter, setContentFilter] = useCanvasState<string>("content", "all");
  const [query, setQuery] = useCanvasState<string>("query", "");

  const lowerQuery = query.trim().toLowerCase();

  const filtered = ALL_REVIEWS.filter((r) => {
    if (ratingFilter !== "all" && ratingBucket(r.rating) !== ratingFilter) return false;
    if (sourceFilter !== "all" && r.source !== sourceFilter) return false;
    const hasExt = Object.keys(r.ext).length > 0;
    if (contentFilter === "with_extraction" && !hasExt) return false;
    if (contentFilter === "empty" && hasExt) return false;
    if (contentFilter === "with_warnings" && (!r.warns || r.warns.length === 0)) return false;
    if (lowerQuery) {
      const hay = `${r.restaurant} ${r.desc}`.toLowerCase();
      if (!hay.includes(lowerQuery)) return false;
    }
    return true;
  });

  const stats = {
    total: ALL_REVIEWS.length,
    showing: filtered.length,
    withExtraction: filtered.filter((r) => Object.keys(r.ext).length > 0).length,
    empty: filtered.filter((r) => Object.keys(r.ext).length === 0).length,
    withWarnings: filtered.filter((r) => r.warns && r.warns.length > 0).length,
  };

  return (
    <Stack gap={20}>
      <Stack gap={6}>
        <H1>All 146 reviews · v2 extractions</H1>
        <Text tone="secondary">
          Browse every review and its structured extraction. Filters persist
          across canvas rebuilds. Click any row to expand the full output.
        </Text>
      </Stack>

      {/* Filter strip */}
      <Stack gap={10}>
        <Row gap={6} wrap align="center">
          <Text size="small" tone="tertiary" weight="medium" style={{ minWidth: 60 }}>
            rating
          </Text>
          {RATING_OPTIONS.map((opt) => (
            <Pill
              key={opt.value}
              active={ratingFilter === opt.value}
              onClick={() => setRatingFilter(opt.value)}
            >
              {opt.label}
            </Pill>
          ))}
        </Row>
        <Row gap={6} wrap align="center">
          <Text size="small" tone="tertiary" weight="medium" style={{ minWidth: 60 }}>
            source
          </Text>
          {SOURCE_OPTIONS.map((opt) => (
            <Pill
              key={opt.value}
              active={sourceFilter === opt.value}
              onClick={() => setSourceFilter(opt.value)}
            >
              {opt.label}
            </Pill>
          ))}
        </Row>
        <Row gap={6} wrap align="center">
          <Text size="small" tone="tertiary" weight="medium" style={{ minWidth: 60 }}>
            content
          </Text>
          {CONTENT_OPTIONS.map((opt) => (
            <Pill
              key={opt.value}
              active={contentFilter === opt.value}
              onClick={() => setContentFilter(opt.value)}
            >
              {opt.label}
            </Pill>
          ))}
        </Row>
        <Row gap={6} align="center">
          <Text size="small" tone="tertiary" weight="medium" style={{ minWidth: 60 }}>
            search
          </Text>
          <TextInput
            value={query}
            onChange={(v: string) => setQuery(v)}
            placeholder="restaurant name or review text..."
            style={{ flex: 1 }}
          />
        </Row>
      </Stack>

      {/* Stats row */}
      <Grid columns={4} gap={12}>
        <Stat value={`${stats.showing} / ${stats.total}`} label="Showing / total" />
        <Stat
          value={stats.withExtraction.toString()}
          label="With extraction"
          tone="success"
        />
        <Stat value={stats.empty.toString()} label="Empty {}" />
        <Stat
          value={stats.withWarnings.toString()}
          label="With warnings"
          tone={stats.withWarnings > 0 ? "warning" : "success"}
        />
      </Grid>

      {filtered.length === 0 ? (
        <Callout tone="info">No reviews match the current filters.</Callout>
      ) : (
        <Stack gap={6}>
          {filtered.map((r) => (
            <ReviewRow key={r.idx} record={r} />
          ))}
        </Stack>
      )}
    </Stack>
  );
}

// ---------------------------------------------------------------------------

function ReviewRow({ record }: { record: ReviewRecord }) {
  const hasExt = Object.keys(record.ext).length > 0;
  const hasWarns = record.warns && record.warns.length > 0;

  return (
    <Card collapsible defaultOpen={false}>
      <CardHeader
        trailing={
          <Row gap={6} align="center">
            {record.rating !== null && (
              <Pill tone={ratingTone(record.rating)} size="sm">
                {record.rating.toFixed(1)}\u2605
              </Pill>
            )}
            <Pill size="sm" tone="neutral">
              {record.source}
            </Pill>
            <Text tone="tertiary" size="small">
              {record.desc_len} ch
            </Text>
            {hasExt ? (
              <Pill size="sm" tone="success">
                ext
              </Pill>
            ) : (
              <Pill size="sm" tone="neutral">
                {`{}`}
              </Pill>
            )}
            {hasWarns && (
              <Pill size="sm" tone="warning">
                {record.warns.length}w
              </Pill>
            )}
          </Row>
        }
      >
        {`#${String(record.idx).padStart(3, "0")} \u00b7 ${record.restaurant}`}
      </CardHeader>
      <CardBody>
        <Stack gap={14}>
          <Stack gap={4}>
            <Text size="small" weight="semibold" tone="tertiary">
              REVIEW
            </Text>
            {record.desc ? (
              <Text>{record.desc}</Text>
            ) : (
              <Text tone="tertiary" italic>
                (empty review text)
              </Text>
            )}
          </Stack>
          <Divider />
          <Stack gap={4}>
            <Row gap={8} align="center">
              <Text size="small" weight="semibold" tone="tertiary">
                EXTRACTED
              </Text>
              <Text size="small" tone="tertiary">
                {record.in_tok} in \u00b7 {record.out_tok} out tok
              </Text>
            </Row>
            {hasExt ? (
              <ExtractionView extracted={record.ext} />
            ) : (
              <Text tone="tertiary" italic>
                {`{}  \u2014 model correctly emitted empty (review had no extractable content)`}
              </Text>
            )}
          </Stack>
          {hasWarns && (
            <>
              <Divider />
              <Stack gap={4}>
                <Text size="small" weight="semibold" tone="tertiary">
                  VALIDATION WARNINGS
                </Text>
                {record.warns.map((w, i) => (
                  <Text key={i} size="small" tone="secondary" italic>
                    {w.split("\n").join(" ").slice(0, 280)}
                  </Text>
                ))}
              </Stack>
            </>
          )}
        </Stack>
      </CardBody>
    </Card>
  );
}

// ---------------------------------------------------------------------------

function ExtractionView({ extracted }: { extracted: Extraction }) {
  return (
    <Stack gap={10}>
      {Object.entries(extracted).map(([section, value]) => (
        <SectionBlock key={section} name={section} value={value} />
      ))}
    </Stack>
  );
}

function SectionBlock({ name, value }: { name: string; value: unknown }) {
  return (
    <Stack gap={4}>
      <Text size="small" weight="semibold">
        {name}
      </Text>
      <SectionContent name={name} value={value} />
    </Stack>
  );
}

function SectionContent({ name, value }: { name: string; value: unknown }) {
  if (name === "dishes" && Array.isArray(value)) {
    return <DishesList dishes={value as Array<Record<string, unknown>>} />;
  }
  if (name === "immune_flags" && value && typeof value === "object" && !Array.isArray(value)) {
    return <ImmuneFlagsView flags={value as Record<string, { severity?: string; span?: string }>} />;
  }
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return <KeyValueRows obj={value as Record<string, unknown>} />;
  }
  return <Text size="small">{String(value)}</Text>;
}

function KeyValueRows({ obj }: { obj: Record<string, unknown> }) {
  const entries = Object.entries(obj);
  return (
    <Stack gap={3}>
      {entries.map(([k, v]) => {
        if (k === "span") {
          return (
            <Row key={k} gap={8} align="start">
              <Text tone="tertiary" size="small" weight="medium" style={{ minWidth: 110 }}>
                span
              </Text>
              <Text size="small" italic tone="secondary">
                "{String(v)}"
              </Text>
            </Row>
          );
        }
        if (Array.isArray(v)) {
          return (
            <Row key={k} gap={8} align="start" wrap>
              <Text tone="tertiary" size="small" weight="medium" style={{ minWidth: 110 }}>
                {k}
              </Text>
              <Row gap={4} wrap>
                {v.map((item, i) => (
                  <Pill key={i} size="sm">
                    {typeof item === "object" ? JSON.stringify(item) : String(item)}
                  </Pill>
                ))}
              </Row>
            </Row>
          );
        }
        if (v && typeof v === "object") {
          return (
            <Row key={k} gap={8} align="start">
              <Text tone="tertiary" size="small" weight="medium" style={{ minWidth: 110 }}>
                {k}
              </Text>
              <Stack gap={2}>
                <KeyValueRows obj={v as Record<string, unknown>} />
              </Stack>
            </Row>
          );
        }
        return (
          <Row key={k} gap={8} align="center">
            <Text tone="tertiary" size="small" weight="medium" style={{ minWidth: 110 }}>
              {k}
            </Text>
            <Code>{String(v)}</Code>
          </Row>
        );
      })}
    </Stack>
  );
}

function DishesList({ dishes }: { dishes: Array<Record<string, unknown>> }) {
  return (
    <Stack gap={6}>
      {dishes.map((d, i) => {
        const taste = Array.isArray(d.taste_descriptors)
          ? (d.taste_descriptors as string[]).join(", ")
          : null;
        return (
          <Row key={i} gap={6} wrap align="center">
            <Pill
              tone={sentimentTone(String(d.sentiment ?? ""))}
              active
              size="sm"
            >
              {String(d.sentiment ?? "?")}
            </Pill>
            <Text size="small" weight="semibold">
              {String(d.name ?? "")}
            </Text>
            {d.category && (
              <Text size="small" tone="tertiary">
                ({String(d.category)})
              </Text>
            )}
            {d.role && (
              <Pill size="sm">{String(d.role)}</Pill>
            )}
            {taste && (
              <Text size="small" tone="secondary" italic>
                {taste}
              </Text>
            )}
            {d.temperature_served && (
              <Code>{String(d.temperature_served)}</Code>
            )}
          </Row>
        );
      })}
    </Stack>
  );
}

function ImmuneFlagsView({
  flags,
}: {
  flags: Record<string, { severity?: string; span?: string }>;
}) {
  return (
    <Stack gap={4}>
      {Object.entries(flags).map(([flag, info]) => (
        <Row key={flag} gap={8} align="start" wrap>
          <Pill tone={severityTone(String(info.severity ?? ""))} active size="sm">
            {String(info.severity ?? "?")}
          </Pill>
          <Text size="small" weight="semibold">
            {flag}
          </Text>
          {info.span && (
            <Text size="small" italic tone="secondary" style={{ flex: 1, minWidth: 0 }}>
              "{info.span}"
            </Text>
          )}
        </Row>
      ))}
    </Stack>
  );
}
"""


def main():
    data_path = ROOT / "data/llm_cache/sample/canvas_full_data.json"
    with open(data_path) as f:
        data_str = f.read()

    # Escape for embedding inside a JS template-literal string:
    #   backtick     -> escaped backtick
    #   backslash    -> escaped backslash (must come first when injecting)
    #   ${           -> escaped to avoid interpolation
    # Since data_str is already valid JSON (no raw backticks, no raw ${),
    # the only realistic risk is the backslash escape sequences inside
    # JSON strings (e.g. \" \\) — those are already valid JS string
    # escapes, so we can paste verbatim.
    escaped = (
        data_str
        .replace("\\", "\\\\")
        .replace("`", "\\`")
        .replace("${", "\\${")
    )

    out = TEMPLATE.replace("__DATA_JSON__", escaped)

    # Write to a workspace-local staging location; an external step copies
    # the file into the cursor projects canvases directory.
    staging = ROOT / "data/llm_cache/sample/zomato-extraction-all-reviews.canvas.tsx"
    staging.write_text(out)
    size_kb = staging.stat().st_size / 1024
    print(f"Wrote staging file {staging} ({size_kb:.1f} KB)")
    print(f"Target canvas path: {CANVAS_PATH}")


if __name__ == "__main__":
    main()
